SELECT
  EVT_CODE,
  EVT_ORG,
  EVT_DESC,
  EVT_MRC,
  R5O7.O7GET_DESC('EN', 'OBJ', EVT_LOCATION, '', '') EVT_LOCATION_DESC,
  EVT_OBJECT,
  R5O7.O7GET_DESC('EN', 'OBJ', EVT_OBJECT, '', '') EVT_OBJECT_DESC,
  EVT_CREATED,
  floor(SYSDATE - EVT_CREATED) DAYS_SINCE_CREATED,
  to_char(substr((SELECT ADD_TEXT FROM (
    SELECT R5REP.TRIMHTML(ADD_CODE, ADD_RENTITY, ADD_TYPE, ADD_LANG, ADD_LINE) ADD_TEXT
    FROM R5ADDETAILS 
    WHERE ADD_CODE = EVT_CODE 
    ORDER BY ADD_LINE DESC)
  WHERE ROWNUM = 1), 1, 32767)) LATEST_COMMENT
FROM R5EVENTS
WHERE EVT_TYPE = 'JOB'
and EVT_JOBTYPE = 'CM'
AND EVT_RSTATUS = 'R'
AND EVT_STATUS <> 'FC'
AND EVT_MRC IN ('641','643','644','647')