SELECT
    EVT_MRC,
    COUNT(CASE WHEN EVT_COMPLETED < ONE_YEAR THEN 1 END) DONE_IN_FREQ,
    COUNT(CASE WHEN EVT_COMPLETED > ONE_YEAR AND EVT_COMPLETED < REG_DUE_DATE THEN 1 END) DONE_IN_COMPLIANCE,
    COUNT(CASE WHEN EVT_COMPLETED > REG_DUE_DATE THEN 1 END) OUTSIDE_COMPLIANCE
FROM
    (SELECT
        A.*,
        CASE
          WHEN EVT_PPM = 'PR-OOSSTA-INSP' AND R5O7.O7GET_DESC('EN', 'OBJ', EVT_OBJECT, '', '') LIKE '%TRANSMISSION%' THEN ADD_MONTHS(PREVIOUS, 39)
          WHEN REG_PERIOD IN ('1M', '3M', '6M', '1Y', '3Y', '5Y', '6Y', '10Y') THEN ADD_MONTHS(PREVIOUS, DECODE(EVT_PERIODUOM, 'M', 1, 'Y', 12) * (EVT_FREQ)) + 15
          WHEN REG_PERIOD = '6M NTE 7.5M' THEN ADD_MONTHS(PREVIOUS, 7) + 15
          WHEN REG_PERIOD = '1Y NTE 15M' AND EXTRACT(YEAR FROM ADD_MONTHS(PREVIOUS, 15)) - EXTRACT(YEAR FROM PREVIOUS) = 1 THEN ADD_MONTHS(PREVIOUS, 15)
          WHEN REG_PERIOD = '1Y NTE 15M' THEN ADD_MONTHS(TRUNC(PREVIOUS, 'YEAR') - 1, 24)
          WHEN REG_PERIOD = '3Y NTE 39M' AND EXTRACT(YEAR FROM ADD_MONTHS(PREVIOUS, 39)) - EXTRACT(YEAR FROM PREVIOUS) = 3 THEN ADD_MONTHS(PREVIOUS, 39)
          WHEN REG_PERIOD = '3Y NTE 39M' THEN ADD_MONTHS(TRUNC(PREVIOUS, 'YEAR') - 1, 48)
          ELSE ADD_MONTHS(PREVIOUS, DECODE(EVT_PERIODUOM, 'M', 1, 'Q', 3, 'Y', 12) * (EVT_FREQ)) + 15
        END REG_DUE_DATE
    FROM 
        (SELECT
            E.EVT_CODE,
            E.EVT_DESC,
            E.EVT_MRC,
            E.EVT_OBJECT,
            E.EVT_PPM,
            E.EVT_FREQ,
            E.EVT_PERIODUOM,
            RP.PRV_VALUE REG_PERIOD,
            E.EVT_COMPLETED,
            TRUNC(MAX(E2.EVT_COMPLETED)) PREVIOUS,
            LAST_DAY(ADD_MONTHS(TRUNC(MAX(E2.EVT_COMPLETED)), 12)) ONE_YEAR
        FROM
            R5EVENTS E
            JOIN R5PPMS PM
                ON E.EVT_PPM = PM.PPM_CODE
            LEFT JOIN R5PROPERTYVALUES RP
                ON E.EVT_PPM || '#0' = RP.PRV_CODE
                AND RP.PRV_PROPERTY = 'REGPERD'
            LEFT JOIN R5EVENTS E2
                ON E2.EVT_OBJECT = E.EVT_OBJECT
                AND E2.EVT_DUE < E.EVT_DUE
            JOIN R5PPMS PM2
                ON E2.EVT_PPM = PM2.PPM_CODE
        WHERE
            E.EVT_DUE >= DATE '2023-01-01'
            AND E.EVT_PERIODUOM NOT IN ('D', 'W')
            AND PM.PPM_JOBTYPE = 'REGUL'
            AND (E.EVT_PPM = E2.EVT_PPM 
                  OR (((E.EVT_PERIODUOM IN ('M','Q') AND E2.EVT_PERIODUOM = 'Y')
                        OR (E.EVT_PERIODUOM = 'Y' AND E2.EVT_PERIODUOM = 'Y' AND E.EVT_FREQ < E2.EVT_FREQ))
                        AND PM.PPM_NESTED = PM2.PPM_NESTED)
                  OR (E.EVT_MRC IN ('641','643','644','647') AND PM2.PPM_UDFCHAR07 = E.EVT_UDFCHAR07))
            AND E2.EVT_RSTATUS = 'C'
            AND E2.EVT_STATUS <> 'CANC'
        GROUP BY
            E.EVT_CODE,
            E.EVT_DESC,
            E.EVT_MRC,
            E.EVT_OBJECT,
            E.EVT_PPM,
            E.EVT_FREQ,
            E.EVT_PERIODUOM,
            RP.PRV_VALUE,
            E.EVT_COMPLETED) A)
GROUP BY EVT_MRC