SELECT
    TO_CHAR(UA.OSF_DATE, 'Q') QUARTER,
    OL.WG_OSF_RUNNUM,
    OL.WG_OSF_STARTSEQ,
    INITCAP(
        TO_CHAR(
            ADD_MONTHS(
                TO_DATE(OL.WG_OSF_STARTSEQ, 'MM'),
                3 * (TO_NUMBER(TO_CHAR(UA.OSF_DATE, 'Q')) - 1)
            ), 
            'MONTH'
        )
    ) MONTH_DUE,
    TO_CHAR(MAX(UA.OSF_DATE), 'MM/DD/YYYY') OSF_DATE
FROM 
    U5ODORSAMPLELOCATIONS OL
    LEFT JOIN U5UTLODORSAMPLE UA
        ON OL.WG_OSF_SITECODE = UA.OSF_FIXEDSITECODE
WHERE OL.WG_OSF_NOTUSED = '-'
AND   OL.WG_OSF_TYPE IN ('FIXED')
AND   (UA.OSF_DATE BETWEEN DATE '2023-01-01' AND DATE '2023-12-31' OR 
      (UA.OSF_DATE > DATE '2023-01-01' AND OL.WG_OSF_STARTSEQ <> TO_NUMBER(TO_CHAR(UA.OSF_DATE, 'MM')) - (3 * (TO_NUMBER(TO_CHAR(UA.OSF_DATE, 'Q')) - 1))))
AND   OL.WG_OSF_RUNNUM IS NOT NULL
GROUP BY
    TO_CHAR(UA.OSF_DATE, 'Q'),
    OL.WG_OSF_RUNNUM,
    OL.WG_OSF_STARTSEQ
ORDER BY 1, 3, TO_NUMBER(OL.WG_OSF_RUNNUM)